author: flightagent
date: 2026-05-28
version: v0.0.1
copyright: flightagent.pro@gmail.com
license: MIT
contact: flightagent.pro@gmail.com
web: flightagent.com
keyboard:
  buttons_count: 12
  knobs_count: 4
  layers:
    "0":
      bindings:
        - key:
            type: button
            index: 0
          msfs_action: HEADING_BUG_INC
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 4
        - key:
            type: button
            index: 1
          msfs_action: HEADING_BUG_DEC
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 5
        - key:
            type: button
            index: 2
          msfs_action: ALTITUDE_BUG_INC
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 6
        - key:
            type: button
            index: 3
          msfs_action: ALTITUDE_BUG_DEC
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 7
        - key:
            type: button
            index: 4
          msfs_action: SPOILERS_ARM_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 6
        - key:
            type: button
            index: 5
          msfs_action: GEAR_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 8
        - key:
            type: button
            index: 6
          msfs_action: FLAPS_INC
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 9
        - key:
            type: button
            index: 7
          msfs_action: FLAPS_DEC
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 10
        - key:
            type: button
            index: 8
          msfs_action: PARKING_BRAKES
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 11
        - key:
            type: button
            index: 9
          msfs_action: STROBES_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 12
        - key:
            type: button
            index: 10
          msfs_action: LANDING_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 13
        - key:
            type: button
            index: 11
          msfs_action: BEACON_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 14
        - key:
            type: knob
            index: 0
            action: ccw
          msfs_action: NAV_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 15
        - key:
            type: knob
            index: 0
            action: cw
          msfs_action: TAXI_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 16
        - key:
            type: knob
            index: 0
            action: press
          msfs_action: LOGO_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 7
                code: 17
        - key:
            type: knob
            index: 1
            action: ccw
          msfs_action: CABIN_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 18
        - key:
            type: knob
            index: 1
            action: cw
          msfs_action: PANEL_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 19
        - key:
            type: knob
            index: 1
            action: press
          msfs_action: PEDESTAL_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 20
        - key:
            type: knob
            index: 2
            action: ccw
          msfs_action: GLARESHIELD_LIGHTS_TOGGLE
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 21
        - key:
            type: knob
            index: 2
            action: cw
          msfs_action: TOGGLE_MASTER_BATTERY
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 22
        - key:
            type: knob
            index: 2
            action: press
          msfs_action: TOGGLE_MASTER_ALTERNATOR
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 23
        - key:
            type: knob
            index: 3
            action: ccw
          msfs_action: TOGGLE_MASTER_IGNITION_SWITCH
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 24
        - key:
            type: knob
            index: 3
            action: cw
          msfs_action: TOGGLE_FUEL_VALVE_ENG1
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 25
        - key:
            type: knob
            index: 3
            action: press
          msfs_action: TOGGLE_WATER_RUDDER
          macro:
            type: keyboard
            presses:
              - modifiers: 0
                code: 26
      led:
        mode: press
        color: orange
